apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: custom-notebook
  namespace: custom-notebook-demo
  annotations:
    opendatahub.io/notebook-image-name: Custom Notebook
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  tags:
  - name: v0.1
    from:
      kind: ImageStreamTag
      name: latest
  lookupPolicy:
    local: false
