apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# nameSuffix: -test

labels:
- includeSelectors: false
  pairs:
    opendatahub.io/dashboard: "true"

resources:
  - custom-workbench-is.yaml
